### ISSUE TITLE
Keyerror: 0 

### ISSUE THREAD

**Issue by sam1am** [flaeppe/couchbot#2]
I get this error when trying to run the bot: 

`Traceback (most recent call last):                                                                                                                                      
  File "/usr/local/bin/couchbot", line 11, in <module>                                                                                                                  
    sys.exit(main())                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/couchbot/__init__.py", line 87, in main                                                                                  
    start()                                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/couchbot/__init__.py", line 73, in start                                                                                 
    bot_id = sc.server.users[0].id                                                                                                                                      
KeyError: 0 `

**Comment by webbrain-one** [comment]
Hey! I’ve opened [PR #5](https://github.com/flaeppe/couchbot/pull/5) to fix this `KeyError: 0`. It addresses the startup crash by handling the server user list safely instead of assuming `users[0]` always exists.
